// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qicknsbkdxykidkceeyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpY2tuc2JrZHh5a2lka2NlZXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzQyNzksImV4cCI6MjA2NTc1MDI3OX0.v-9XQ48Mkmf6qalhV57Y_G7LKjGftlHsiHq3q-oejJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);